services:
<<<<<<< HEAD
<<<<<<< HEAD
  trilogy_app:
    build: .
    image: trilogy_app_image:latest
    container_name: trilogy_app_container
    ports:
      - "8080:${PORT}"
    env_file:
      - .env
=======
  solana_agents:
    build:
      context: ./solana_agents
      dockerfile: Dockerfile
    container_name: solana_agents
    environment:
      - SOLANA_RPC_URL=${SOLANA_RPC_URL}
      - SOLANA_PRIVATE_KEY=${SOLANA_PRIVATE_KEY}
      - MONGO_DETAILS=${MONGO_DETAILS}
=======
  mongo:
    image: mongo:latest
    container_name: qmcs-mongo
>>>>>>> 4632db42 (Add Argus as submodule)
    ports:
      - "27017:27017"

  solana_agents:
    build: ./solana_agents
    container_name: qmcs-solana_agents
    ports:
      - "5106:4000"

  argus_service:
    build: ./argus_service
    container_name: argus_service
    ports:
      - "5101:5000"

  oracle_service:
    build: ./oracle_service
    container_name: oracle_service
    ports:
      - "5102:5000"

  openai_service:
    build: ./openai_service
    container_name: openai_service
    ports:
      - "5103:5000"
    # Add environment file if needed:
    env_file:
      - .env
    volumes:
      - chroma_data:/app/chroma_storage

  quant_service:
    build: ./quant_service
    container_name: quant_service
    ports:
      - "5104:5000"

<<<<<<< HEAD
networks:
  default:
    driver: bridge
>>>>>>> ad2001f2 (Update: Added logging, fixed MongoDB connection, updated Docker compose, and initial wallet stats endpoint)
=======
  ragchain_service:
    build: ./ragchain_service
    container_name: ragchain_service
    ports:
      - "5105:5000"

volumes:
  chroma_data:
>>>>>>> 4632db42 (Add Argus as submodule)
