version: "3.8"

services:
  solana_agents:
    build:
      context: ./solana_agents
      dockerfile: Dockerfile
    container_name: solana_agents
    ports:
      - "4000:4000"
    networks:
      - app-network
    restart: unless-stopped

  ragchain-service:
    build:
      context: ./ragchain_service
      dockerfile: Dockerfile
    container_name: ragchain_service
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - mongo
    restart: unless-stopped

  quant-service:
    build:
      context: ./quant_service
      dockerfile: Dockerfile
    container_name: quant_service
    ports:
      - "7000:7000"
    networks:
      - app-network
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: local_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mongo_data:

networks:
  app-network:
    name: solais-network
